### ISSUE TITLE
error with latest build

### ISSUE THREAD

**Issue by Daeveren** [chancedj/LockedOut#65]
Message: Interface\AddOns\LockedOut\Configuration.lua:49: attempt to concatenate field 'icon' (a nil value)
Time: 10/30/17 09:53:09
Count: 1
Stack: Interface\AddOns\LockedOut\Configuration.lua:49: attempt to concatenate field 'icon' (a nil value)
(tail call): ?
Interface\AddOns\LockedOut\Configuration.lua:49: in function `getConfigOptions'
Interface\AddOns\LockedOut\Configuration.lua:312: in function <Interface\AddOns\LockedOut\Configuration.lua:295>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:644: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by chancedj** [comment]
This should be fixed now.  thanks for finding this.  This is one of those where the first round doesn't find the information so it finds it on the second pass.

**Comment by Daeveren** [comment]
not fixed:

Message: Interface\AddOns\LockedOut\Configuration.lua:53: attempt to concatenate field 'icon' (a nil value)
Time: 10/30/17 16:28:03
Count: 1
Stack: Interface\AddOns\LockedOut\Configuration.lua:53: attempt to concatenate field 'icon' (a nil value)
(tail call): ?
Interface\AddOns\LockedOut\Configuration.lua:53: in function `getConfigOptions'
Interface\AddOns\LockedOut\Configuration.lua:316: in function <Interface\AddOns\LockedOut\Configuration.lua:299>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:644: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by chancedj** [comment]
ok, thanks.  i'll take a look again. 

when is this happening, on player load?  or later on?

**Comment by Daeveren** [comment]
player load

**Comment by chancedj** [comment]
i can get it to happen (though i can't get the error to pop up) if i delete the cache folder.  it basically keeps the window from opening up on hover until i reload ui.  at that point i can see the information.

going to investigate a little more and see if it's in the config menu setup or if it's actually in the minimap.

What addon are you using to catch the exceptions - it's odd i'm not seeing the same (i removed all the addons but elvui and lockedout and still not getting the popup).

**Comment by Daeveren** [comment]
Logged on my monk (which had LO loaded) - no error. I've seen that my druid has no Karazhan kill on the LO tooltip, so I logged him to go to Karazhan. Logged on my druid, went to Karazhan, proved out he killed the 1st boss already - proves out the druid did not had LO loaded; while in Karazhan, done a reload with the LO enabled (I'm enabling addons through ACP) - after loading screen completed, error popped up:

![2017-10-30 21_57_22-greenshot](https://user-images.githubusercontent.com/6321337/32192809-f88c6ba0-bdbd-11e7-828a-3794fbde6c5a.jpg)



I'm displaying the LUA errors with AdvancedInterfaceOptions

![2017-10-30 22_02_41-world of warcraft](https://user-images.githubusercontent.com/6321337/32192869-21321ff0-bdbe-11e7-8a79-0e8ea0d28254.jpg)

**Comment by chancedj** [comment]
thanks.  i get errors sometimes and sometimes i don't ( the tooltip just doesn't want to work ) so i'll install that and see if it makes it happen more consistent.

the only change was to add pet charms to the currency.  i'll back out that change and see if it's helps.  really odd.

**Comment by Daeveren** [comment]
Also just logged on my mage now (he was parked in Dalaran), first thing I see is:

Message: Interface\AddOns\LockedOut\Configuration.lua:53: attempt to concatenate field 'icon' (a nil value)
Time: 10/30/17 23:32:35
Count: 1
Stack: Interface\AddOns\LockedOut\Configuration.lua:53: attempt to concatenate field 'icon' (a nil value)
(tail call): ?
Interface\AddOns\LockedOut\Configuration.lua:53: in function `getConfigOptions'
Interface\AddOns\LockedOut\Configuration.lua:316: in function <Interface\AddOns\LockedOut\Configuration.lua:299>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:644: in function <Interface\AddOns\Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by chancedj** [comment]
ok.  get the latest.  i removed the petcharm code.  that should reosolve the issue now.  seems it doesn't return data all the time in a timely manner.
